### ISSUE TITLE
Scrolling passed through navbar

### ISSUE THREAD

**Issue by gevezex** [frontendfunn/semantic-ui-admin-dashboard-template#1]
When I scroll down and up the scrollbar goes through the navbar. Is there a way to stop that behaviour? This is both tested on chrome and safari browsers.

I've attached a screenshot.

<img width="436" alt="Screenshot 2020-03-22 at 14 20 37" src="https://user-images.githubusercontent.com/4493063/77250516-c19da280-6c48-11ea-96c7-3463c462f338.png">

**Comment by frontendfunn** [comment]
@gevezex Is this behavior same with the official site...

**Comment by gevezex** [comment]
I am not sure as your implementation is a mix of components. That's why I wanted to know if there is a fix within your code.

**Comment by frontendfunn** [comment]
![Untitled](https://user-images.githubusercontent.com/43083926/77251570-148d4f00-6c75-11ea-8fec-7b1dc8b58b3a.png)

Image from the official Site..

**Comment by gevezex** [comment]
Thnx. So there is no way to fix this?

**Comment by frontendfunn** [comment]
```
.main-content {
  margin-top: 40px;
  height: calc(100% - 40px); // topnavbar is 40px height
  overflow-y: auto;
}

.pusher {
  overflow: hidden;
  height: 100%;
}
```

try adding this CSS Rules.. to your css

**Comment by frontendfunn** [comment]
[Scrollbar Issue Fixed Branch](https://github.com/frontendfunn/semantic-ui-admin-dashboard-template/tree/scrollbar_issue_fixed)

Please Check the Updated Code on this branch

**Comment by frontendfunn** [comment]
@gevezex Please Check the Updated code in the new branch.

**Comment by gevezex** [comment]
I adapted the css file and it worked like a charm. Thank your very much! 
I will close this ticket now!
